/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 3d_objects.glb
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d_objects.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-153.71, -59.99, 306.08]} rotation={[0.15, -0.04, -0.27]} scale={0.86}>
          <mesh geometry={nodes.Cylinder_4.geometry} material={materials['default']} position={[-14.56, 41.51, 5.45]} rotation={[0.26, 0.02, 0.08]} />
          <mesh geometry={nodes.Cylinder_3.geometry} material={materials['default']} position={[0, 18.91, 0]} />
          <mesh geometry={nodes.Cylinder_2.geometry} material={materials['default']} position={[-0.39, -30.22, -1.03]} />
          <mesh geometry={nodes.Cylinder.geometry} material={materials['default']} position={[-0.39, -37.79, -1.03]} />
        </group>
        <group position={[368.86, -246.68, -203.91]} rotation={[-0.15, -0.44, -0.77]} scale={0.9}>
          <mesh geometry={nodes.Torus_8.geometry} material={materials['default']} rotation={[0, 0, -0.26]} />
          <mesh geometry={nodes.Torus_6.geometry} material={materials['default']} rotation={[0, 0, -1.83]} />
          <mesh geometry={nodes.Torus_4.geometry} material={materials['default']} rotation={[0, 0, 2.88]} />
          <mesh geometry={nodes.Torus_2.geometry} material={materials['default']} rotation={[0, 0, 1.31]} />
          <mesh geometry={nodes.Torus_7.geometry} material={materials['default']} rotation={[0, 0, -Math.PI / 3]} />
          <mesh geometry={nodes.Torus_5.geometry} material={materials['default']} rotation={[0, 0, -2.62]} />
          <mesh geometry={nodes.Torus_3.geometry} material={materials['default']} rotation={[0, 0, 2.09]} />
          <mesh geometry={nodes.Torus.geometry} material={materials['default']} rotation={[0, 0, Math.PI / 6]} />
        </group>
        <group position={[-422.26, 12.06, 41.74]} rotation={[0.69, 0.28, 0.49]} scale={0.84}>
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials['default']} position={[0.64, -45.33, 0.71]} />
          <mesh geometry={nodes.Cube.geometry} material={materials['default']} position={[0, -13.67, 0]} />
        </group>
        <group position={[-275.5, -150, 329.71]} rotation={[-0.41, -0.22, -0.22]} scale={0.78}>
          <group position={[-57.89, -24.25, 0.48]}>
            <mesh geometry={nodes.mesh_19_instance_1.geometry} material={materials['default']} />
            <mesh geometry={nodes.mesh_19_instance_2.geometry} material={materials['default']} position={[10, 0, 0]} />
            <mesh geometry={nodes.mesh_19_instance_3.geometry} material={materials['default']} position={[20, 0, 0]} />
            <mesh geometry={nodes.mesh_19_instance_4.geometry} material={materials['default']} position={[30, 0, 0]} />
          </group>
          <mesh geometry={nodes.Rectangle_7.geometry} material={materials['default']} position={[-39.24, 0.91, 0.48]} />
          <mesh geometry={nodes.Rectangle_8.geometry} material={materials['default']} position={[-39.24, 10.75, 2.07]} rotation={[0, 0, -Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_6.geometry} material={materials['default']} position={[-39.24, 11.05, 0.48]} />
          <mesh geometry={nodes.Rectangle_5.geometry} material={materials['default']} position={[-39.24, 21.5, 0.48]} />
          <mesh geometry={nodes.Rectangle_4.geometry} material={materials['default']} position={[-57.89, -24.25, 0.48]} />
          <mesh geometry={nodes.Rectangle_3.geometry} material={materials['default']} position={[-32.79, -36.18, 0.48]} />
          <mesh geometry={nodes.Ellipse_2.geometry} material={materials['default']} position={[47.39, -27.44, 0.49]} />
          <mesh geometry={nodes.Ellipse.geometry} material={materials['default']} position={[27.75, -27.44, 0.49]} />
          <mesh geometry={nodes.Rectangle_2.geometry} material={materials['default']} position={[0, 0, -6.07]} />
        </group>
        <group position={[-381.16, 221.26, -331.52]} rotation={[-0.09, -0.13, 0.44]} scale={[1.93, 1.85, 1.9]}>
          <mesh geometry={nodes.Cylinder_2_1.geometry} material={materials['default']} position={[0.71, 35.73, 40.73]} rotation={[1.92, 0, 0]} />
          <mesh geometry={nodes.Star.geometry} material={materials['default']} position={[0.6, 36.02, 37.55]} rotation={[0.35, 0, 0]} />
          <mesh geometry={nodes.Cylinder_5.geometry} material={materials['default']} position={[-0.19, -68.82, 0.2]} rotation={[Math.PI, 0, 0]} />
          <mesh geometry={nodes.Cube_3.geometry} material={materials['default']} position={[-59.18, 25.54, -1.28]} rotation={[0, 0, Math.PI / 6]} scale={[-1, 1, 1]} />
          <mesh geometry={nodes.Cube_2.geometry} material={materials['default']} position={[59.18, 26.26, -1.28]} rotation={[0, 0, -Math.PI / 6]} />
          <mesh geometry={nodes.Cube_1.geometry} material={materials['default']} position={[-0.21, 34.23, 0]} />
        </group>
        <group position={[-21.07, -169.97, -54.63]} rotation={[0, 0, 0.26]} scale={0.96}>
          <group position={[-3.72, 0, -16.4]} rotation={[0.09, 0, -Math.PI / 9]}>
            <mesh geometry={nodes['%'].geometry} material={materials['default']} position={[-27.2, -43.34, 1.56]} />
            <mesh geometry={nodes['%_1'].geometry} material={materials['default']} position={[-27.2, -43.34, 1.56]} />
            <mesh geometry={nodes['%_2'].geometry} material={materials['default']} position={[-27.2, -43.34, 1.56]} />
            <mesh geometry={nodes.Shape.geometry} material={materials['default']} position={[-41.29, -75.02, -5.56]} />
          </group>
          <group position={[20.39, -1.29, 10.58]} rotation={[-0.17, -0.02, 0.08]}>
            <mesh geometry={nodes.Ellipse_2_2.geometry} material={materials['default']} position={[0.86, 58.75, 3.11]} />
            <mesh geometry={nodes.Ellipse_6.geometry} material={materials['default']} position={[0.86, 58.75, 2.59]} />
            <mesh geometry={nodes['%_3'].geometry} material={materials['default']} position={[-27.2, -43.34, 1.56]} />
            <mesh geometry={nodes['%_4'].geometry} material={materials['default']} position={[-27.2, -43.34, 1.56]} />
            <mesh geometry={nodes['%_5'].geometry} material={materials['default']} position={[-27.2, -43.34, 1.56]} />
            <mesh geometry={nodes.Shape_1.geometry} material={materials['default']} position={[-41.29, -75.02, -5.56]} />
          </group>
        </group>
        <group position={[-21.71, 134.65, 120.37]} rotation={[-0.55, 0.74, -0.83]} scale={2.42}>
          <mesh geometry={nodes.Cube_4.geometry} material={materials['default']} position={[38.24, 1.89, -54.33]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
          <mesh geometry={nodes.Cylinder_6.geometry} material={materials['default']} position={[0.69, 1.65, -56.2]} rotation={[-Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder_2_2.geometry} material={materials['default']} position={[-1.19, -3.22, 15.59]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Torus_1.geometry} material={materials['default']} position={[0, 0, 37.58]} scale={0.73} />
          <mesh geometry={nodes.Cylinder_7.geometry} material={materials['default']} position={[0.2, -0.91, -35.39]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
        </group>
        <group position={[354.93, 276.53, 26.82]} rotation={[0.11, -0.04, -0.39]} scale={1.1}>
          <group position={[0.01, -18.08, 1.54]}>
            <mesh geometry={nodes.mesh_47_instance_1.geometry} material={materials['default']} position={[0, 40, 0]} />
            <mesh geometry={nodes.mesh_47_instance_2.geometry} material={materials['default']} position={[20, 34.64, 0]} rotation={[0, 0, -Math.PI / 6]} />
            <mesh geometry={nodes.mesh_47_instance_3.geometry} material={materials['default']} position={[34.64, 20, 0]} rotation={[0, 0, -Math.PI / 3]} />
            <mesh geometry={nodes.mesh_47_instance_4.geometry} material={materials['default']} position={[40, 0, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.mesh_47_instance_5.geometry} material={materials['default']} position={[34.64, -20, 0]} rotation={[0, 0, -2.09]} />
            <mesh geometry={nodes.mesh_47_instance_6.geometry} material={materials['default']} position={[20, -34.64, 0]} rotation={[0, 0, -2.62]} />
            <mesh geometry={nodes.mesh_47_instance_7.geometry} material={materials['default']} position={[0, -40, 0]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes.mesh_47_instance_8.geometry} material={materials['default']} position={[-20, -34.64, 0]} rotation={[0, 0, 2.62]} />
            <mesh geometry={nodes.mesh_47_instance_9.geometry} material={materials['default']} position={[-34.64, -20, 0]} rotation={[0, 0, 2.09]} />
            <mesh geometry={nodes.mesh_47_instance_10.geometry} material={materials['default']} position={[-40, 0, 0]} rotation={[0, 0, Math.PI / 2]} />
            <mesh geometry={nodes.mesh_47_instance_11.geometry} material={materials['default']} position={[-34.64, 20, 0]} rotation={[0, 0, Math.PI / 3]} />
            <mesh geometry={nodes.mesh_47_instance_12.geometry} material={materials['default']} position={[-20, 34.64, 0]} rotation={[0, 0, Math.PI / 6]} />
          </group>
          <group position={[0.26, -17.69, 0.1]}>
            <mesh geometry={nodes.mesh_48_instance_1.geometry} material={materials['default']} position={[0, 40, 0]} />
            <mesh geometry={nodes.mesh_48_instance_2.geometry} material={materials['default']} position={[40, 0, 0]} rotation={[0, 0, -Math.PI / 2]} />
            <mesh geometry={nodes.mesh_48_instance_3.geometry} material={materials['default']} position={[0, -40, 0]} rotation={[0, 0, -Math.PI]} />
            <mesh geometry={nodes.mesh_48_instance_4.geometry} material={materials['default']} position={[-40, 0, 0]} rotation={[0, 0, Math.PI / 2]} />
          </group>
          <mesh geometry={nodes.Cube_2_1.geometry} material={materials['default']} position={[-3.29, -21.94, 9.43]} rotation={[0, 0, 2.62]} />
          <mesh geometry={nodes.Cube_5.geometry} material={materials['default']} position={[3.54, -10.06, 9.43]} rotation={[0, 0, -Math.PI / 6]} />
          <mesh geometry={nodes.Rectangle_3_1.geometry} material={materials['default']} position={[0.01, -18.08, 1.54]} />
          <mesh geometry={nodes.Rectangle_2_1.geometry} material={materials['default']} position={[0.26, -17.69, 0.1]} />
          <mesh geometry={nodes.Cylinder_3_1.geometry} material={materials['default']} position={[-0.16, 43.33, 0.6]} />
          <mesh geometry={nodes.Cylinder_2_3.geometry} material={materials['default']} position={[-0.16, 49.04, 0.6]} />
          <mesh geometry={nodes.Torus_9.geometry} material={materials['default']} position={[-0.18, 67.16, 0.53]} />
          <mesh geometry={nodes.Cylinder_8.geometry} material={materials['default']} position={[0, -19.64, -4.77]} rotation={[Math.PI / 2, 0, 0]} scale={2.41} />
        </group>
        <group position={[434.17, -72.63, 131.85]} rotation={[-Math.PI / 4, 0.19, 0]} scale={0.85}>
          <group position={[-34.13, -13.45, -3.38]}>
            <mesh geometry={nodes.mesh_56_instance_1.geometry} material={materials['default']} />
            <mesh geometry={nodes.mesh_56_instance_2.geometry} material={materials['default']} position={[24.2, 0, 0]} />
            <mesh geometry={nodes.mesh_56_instance_3.geometry} material={materials['default']} position={[48.4, 0, 0]} />
            <mesh geometry={nodes.mesh_56_instance_4.geometry} material={materials['default']} position={[72.6, 0, 0]} />
          </group>
          <group position={[-34.13, -38.07, -3.38]}>
            <mesh geometry={nodes.mesh_57_instance_1.geometry} material={materials['default']} />
            <mesh geometry={nodes.mesh_57_instance_2.geometry} material={materials['default']} position={[24.2, 0, 0]} />
            <mesh geometry={nodes.mesh_57_instance_3.geometry} material={materials['default']} position={[48.4, 0, 0]} />
            <mesh geometry={nodes.mesh_57_instance_4.geometry} material={materials['default']} position={[72.6, 0, 0]} />
          </group>
          <group position={[-34.13, -63.96, -3.38]}>
            <mesh geometry={nodes.mesh_58_instance_1.geometry} material={materials['default']} />
            <mesh geometry={nodes.mesh_58_instance_2.geometry} material={materials['default']} position={[24.2, 0, 0]} />
            <mesh geometry={nodes.mesh_58_instance_3.geometry} material={materials['default']} position={[48.4, 0, 0]} />
            <mesh geometry={nodes.mesh_58_instance_4.geometry} material={materials['default']} position={[72.6, 0, 0]} />
          </group>
          <mesh geometry={nodes.Rectangle_7_1.geometry} material={materials['default']} position={[-22.82, 11.7, -3.38]} />
          <mesh geometry={nodes.Rectangle_8_1.geometry} material={materials['default']} position={[38.84, 11.7, -3.38]} />
          <mesh geometry={nodes.Rectangle_6_1.geometry} material={materials['default']} position={[14.51, 11.7, -3.38]} />
          <mesh geometry={nodes.Rectangle_5_1.geometry} material={materials['default']} position={[-34.13, -13.45, -3.38]} />
          <mesh geometry={nodes.Rectangle_4_1.geometry} material={materials['default']} position={[-34.13, -38.07, -3.38]} />
          <mesh geometry={nodes.Rectangle_3_2.geometry} material={materials['default']} position={[-34.13, -63.96, -3.38]} />
          <mesh geometry={nodes.Rectangle_2_2.geometry} material={materials['default']} position={[-0.47, 53.94, 8.31]} rotation={[0.7, 0, 0]} scale={[1, 0.85, 1]} />
          <mesh geometry={nodes.Cube_6.geometry} material={materials['default']} position={[0, -26.24, -15.03]} />
        </group>
        <group position={[-171.73, 408.83, -94.5]} rotation={[0.65, 0, 0.34]} scale={0.82}>
          <mesh geometry={nodes.Rectangle_4_2.geometry} material={materials['default']} position={[7.43, 7, -5.78]} rotation={[0.26, 0, 0]} />
          <mesh geometry={nodes.Rectangle_3_3.geometry} material={materials['default']} position={[-0.49, 19.27, -11.59]} rotation={[0.17, 0, 0]} />
          <mesh geometry={nodes.Rectangle_2_3.geometry} material={materials['default']} position={[4.02, 21.13, -19.93]} rotation={[0.09, 0, 0]} />
          <mesh geometry={nodes.Cube_7.geometry} material={materials['default']} position={[-0.93, -3.88, -29.72]} />
        </group>
        <group position={[226.5, -92.65, -248.42]} rotation={[-0.15, -0.57, 0.33]} scale={1.21}>
          <mesh geometry={nodes.Rectangle_2_4.geometry} material={materials['default']} position={[3.4, 20.39, 24.57]} />
          <mesh geometry={nodes.Cylinder_2_4.geometry} material={materials['default']} position={[62.73, 56.83, 7.86]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Cylinder_9.geometry} material={materials['default']} position={[-59.24, 56.83, 7.86]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Ellipse_8.geometry} material={materials['default']} position={[64.77, 29.28, 28.54]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Ellipse_8_1.geometry} material={materials['default']} position={[38.45, 29.28, 28.54]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Ellipse_7.geometry} material={materials['default']} position={[51.91, 16.12, 28.54]} />
          <mesh geometry={nodes.Ellipse_4.geometry} material={materials['default']} position={[51.91, 42.44, 28.54]} />
          <mesh geometry={nodes.Rectangle_4_3.geometry} material={materials['default']} position={[-36.57, 29.28, 28.54]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_4_4.geometry} material={materials['default']} position={[-61.36, 29.28, 28.54]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Rectangle_3_4.geometry} material={materials['default']} position={[-48.96, 16.89, 28.54]} />
          <mesh geometry={nodes.Rectangle_2_5.geometry} material={materials['default']} position={[-48.96, 41.68, 28.54]} />
          <mesh geometry={nodes.Ellipse_3.geometry} material={materials['default']} position={[51.61, 28.68, 27.46]} />
          <mesh geometry={nodes.Ellipse_2_1.geometry} material={materials['default']} position={[-48.93, 28.68, 27.46]} />
          <mesh geometry={nodes.Ellipse_3_1.geometry} material={materials['default']} position={[51.61, 28.68, 26.38]} />
          <mesh geometry={nodes.Ellipse_1.geometry} material={materials['default']} position={[-48.93, 28.68, 26.38]} />
          <mesh geometry={nodes.Cube_8.geometry} material={materials['default']} position={[-0.02, 26.93, -4.21]} />
        </group>
        <group position={[477.86, 102.23, -386.45]} rotation={[0.05, 0.26, -0.17]} scale={1.1}>
          <mesh geometry={nodes.Torus_10.geometry} material={materials['default']} position={[-0.06, 61.04, -4.11]} />
          <mesh geometry={nodes.Sphere.geometry} material={materials['default']} position={[0.51, -55.05, 1.48]} scale={1.22} />
          <mesh geometry={nodes.Cube_9.geometry} material={materials['default']} position={[0, 3.4, 0]} />
        </group>
        <group position={[189.3, 346.84, 53.88]} rotation={[0.45, 0.24, 0.33]} scale={0.83}>
          <mesh geometry={nodes.Rectangle_3_5.geometry} material={materials['default']} position={[-0.94, -8.88, -22]} rotation={[Math.PI, 0, 0]} />
          <mesh geometry={nodes.Rectangle_2_6.geometry} material={materials['default']} position={[48.37, 20.39, 12.13]} />
          <mesh geometry={nodes.Ellipse_5.geometry} material={materials['default']} position={[1.5, -9.74, 26.55]} />
          <mesh geometry={nodes.Cube_10.geometry} material={materials['default']} position={[0, -8.74, -7.59]} />
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.58, 0.69, 0.8]} />
        <PerspectiveCamera makeDefault={false} far={100000} near={5} fov={45} position={[19.08, -17.55, 1664.42]} rotation={[0.03, 0, 0]} />
        <mesh geometry={nodes.Backdrop.geometry} material={materials['default']} position={[-74.5, 652.5, 2514.2]} />
      </group>
    </group>
  )
}

useGLTF.preload('/3d_objects.glb')
